### ISSUE TITLE
hexo博客的gitment评论开启一直失败

### ISSUE THREAD

**Issue by JJXiangJiaoJun** [imsun/gitment#178]
按照教程上配的，我的github pages绑定了个人域名
`https//:hongbb.top`
OAuth配置如下，应该是没有错误的
![](https://user-images.githubusercontent.com/37390337/51407028-c58dea80-1b95-11e9-98d3-622b327f157e.png)

_config.yml的配置如下，保证client_id 和 client_secret没有填错

```
comment:
  gitment:
    enable: true
    owner: 'JJXiangJiaoJun' # 必填项, 你的GitHub ID
    repo: 'JJXiangJiaoJun.github.io' # 必填项  你的存储评论的repo
    oauth:
      client_id: 'd7df3d5d159f81371d76' # 必填项
      client_secret: '3794527fca067871d3795782ae7fd14f94ce3a74' # 必填项
      redirect_uri: # 可以填也可以不填
```
设置后博客上显示　`Error: Comments Not Initialized`

点击　登录　按钮后，无法跳转到github授权界面
浏览器上信息为 `https://hongbb.top/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch`

看起来好像是call-back url填错了,不过我试了 原来的ＵＲＬ也没用

**Comment by zithan** [comment]
作者自己的官方blog一样的问题：Error: Comments Not Initialized

**Comment by puddlejumper26** [comment]
我的也是，我是在 hexo d 之后，刷新页面，页面显示`Error: Comments Not Initialized`，点击`Login`，然后会跳出对话框`[object ProgressEvent]`，点击确定之后，Gitment区域就显示`Logging in...` ，会一直持续下去，并且Gitment区域不能操作

**Comment by adangran** [comment]
同样的问题

**Comment by BlockBB** [comment]
我的也是，昨天弄的，github登陆之后浏览器显示：

[object XMLHttpRequestProgressEvent]，然后一直在转圈。。。loading commetns

**Comment by sherry0429** [comment]
可以看这里 https://sherry0429.github.io/2019/02/12/gitment%E4%BF%AE%E5%A4%8D/

**Comment by RikkaBlue** [comment]
> 可以看这里 https://sherry0429.github.io/2019/02/12/gitment%E4%BF%AE%E5%A4%8D/

你目前博客的gitment就会报``object ProgressEven`` 不知道什么原因，我的icarus也是这种情况

**Comment by fireairforce** [comment]
我也遇到同样问题了 = =

**Comment by kopa-kongpan** [comment]
解决了吗    我也是一样的问题哎     满脑子很糊涂

**Comment by adamhu** [comment]
解决方案参考：https://adamhu.github.io/2019/06/GitHub-Pages%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA%E6%B5%81%E7%A8%8B/

**Comment by Chiang97912** [comment]
目前网上大部分解决方案都失效了，可以使用下面的方法解决：
打开你的blog本地仓库themes\next\layout\_third-party\comments\gitment.ejs将
```
<link rel="stylesheet" href="https://imsun.github.io/gitment/style/default.css">
<script src="https://imsun.github.io/gitment/dist/gitment.browser.js"></script>
```
修改为：
```
<link rel="stylesheet" href="https://billts.site/extra_css/gitment.css">
<script src="https://billts.site/js/gitment.js"></script>
```
上面给出的是gitment汉化版

**Comment by JJXiangJiaoJun** [comment]
说一下本人的 **解决办法** :
我的github pages绑定了个人域名
``https//:hongbb.top``  导致重定向一直错误，我只修改了`` _config.yml `` 中的 ``redirect_uri`` , 就解决了问题，现在使用正常
```yaml
comment:
  gitment:
    enable: true
    owner: 'JJXiangJiaoJun' # 必填项, 你的GitHub ID
    repo: 'JJXiangJiaoJun.github.io' # 必填项  你的存储评论的repo
    oauth:
      client_id: 'd7df3d5d159f81371d76' # 必填项
      client_secret: '3794527fca067871d3795782ae7fd14f94ce3a74' # 必填项
      redirect_uri: https//:hongbb.top    #如果绑定了个人域名，这里一定要填上绑定的个人域名!!!!!!!!!!!!!
```
可以试试将``redirect_uri`` 改成自己绑定的个人域名
